### ISSUE TITLE
Specify an exporter configuration format

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-specs#34]
Most non-library OpenCensus user swill have to load some configuration to initialize the exporters. Specify a common configuration format for the exporters so that OpenCensus community can reuse the same configuration file with different tools.

An initial proposal for the configuration is below. We can also provide parsers in each language to setup the known exporters from the configuration file.

```
exporters:
  prometheus: 
    addr: "localhost:9999"
  stackdriver: 
    project-id: bamboo-cloud-100
  openzipkin: 
    endpoint: "http://localhost:9411/api/v2/spans"
    hostport: "server:5454"
    name: server
```

/cc @bogdandrutu @acetechnologist  @songy23 @adriancole @dinooliva @odeke-em @g-easy
